from tkinter import*
m=Tk()
m.title("PERSONAL INFORMATION")
def result():
    m.destroy()
    x = Tk()
    x.title("CONFIRMATION")
    y=Label(x,text="\n\nASSALAM-O-ALAIKUM \n YOUR INFORMATION HAS BEEN SUBMITTED SUCCESSFULLY!\n\n",font=("Calibri",18)).grid(row=5,column=4)
img3=PhotoImage(file="D:\\welcome.png")
img4=img3.subsample(8,8)
l5=Label(m,image=img3).grid(row=0,column=2)
a=Label(m,text="STUDENT ID",bg="white",fg="black",font=("Comic Sans MS",15)).grid(row=1,column=0,pady=10)
b=Label(m,text="STUDENT NAME",bg="white",fg="black",font=("Comic Sans MS",15)).grid(row=2,column=0,pady=10)
c=Label(m,text="FATHER'S NAME",bg="white",fg="black",font=("Comic Sans MS",15)).grid(row=3,column=0,pady=10)
d=Label(m,text="STUDENT AGE",bg="white",fg="black",font=("Comic Sans MS",15)).grid(row=4,column=0,pady=10)
e=Label(m,text="ADDRESS",bg="white",fg="black",font=("Comic Sans MS",15)).grid(row=5,column=0,pady=10)
f=Label(m,text="GENDER",bg="white",fg="black",font=("Comic Sans MS",15)).grid(row=6,column=0,pady=10)
g=Entry(m).grid(row=1,column=2,columnspan=8,pady=10)
h=Entry(m).grid(row=2,column=2,columnspan=8,pady=10)
i=Entry(m).grid(row=3,column=2,columnspan=8,pady=10)
j=Entry(m).grid(row=4,column=2,columnspan=8,pady=10)
k=Entry(m).grid(row=5,column=2,columnspan=8,pady=10)
l1=Checkbutton(m,text="Male",fg="black",font=("Arial",15)).grid(row=6,column=2,pady=10)
l2=Checkbutton(m,text="Female",fg="black",font=("Arial",15)).grid(row=7,column=2,pady=10)
img=PhotoImage(file="D:\\bunny.png")
img2=img.subsample(10,10)
l4=Label(m,image=img).grid(row=12,column=2)
l3=Button(m,text="SUBMIT",command=result,bg="violet",fg="black",font=("Arial",18)).grid(row=10,column=1,columnspan=3,pady=10)
m.mainloop()